name: Create Tag

on:
  push:
    branches:
      - main
      - dev
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: butlerlogic/action-autotag@1.1.4
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
